wrap <- function(fn) {
  force(fn)
  function(val, ...) fn(val, ...)
}

wrapped_stabilize_arg <- wrap(stabilize_arg)
wrapped_stabilize_arg_scalar <- wrap(stabilize_arg_scalar)
wrapped_stabilize_chr <- wrap(stabilize_chr)
wrapped_stabilize_chr_scalar <- wrap(stabilize_chr_scalar)
wrapped_stabilize_dbl <- wrap(stabilize_dbl)
wrapped_stabilize_dbl_scalar <- wrap(stabilize_dbl_scalar)
wrapped_stabilize_fct <- wrap(stabilize_fct)
wrapped_stabilize_fct_scalar <- wrap(stabilize_fct_scalar)
wrapped_stabilize_int <- wrap(stabilize_int)
wrapped_stabilize_int_scalar <- wrap(stabilize_int_scalar)
wrapped_stabilize_lgl <- wrap(stabilize_lgl)
wrapped_stabilize_lgl_scalar <- wrap(stabilize_lgl_scalar)
wrapped_to_chr <- wrap(to_chr)
wrapped_to_chr_scalar <- wrap(to_chr_scalar)
wrapped_to_dbl <- wrap(to_dbl)
wrapped_to_dbl_scalar <- wrap(to_dbl_scalar)
wrapped_to_fct <- wrap(to_fct)
wrapped_to_fct_scalar <- wrap(to_fct_scalar)
wrapped_to_int <- wrap(to_int)
wrapped_to_int_scalar <- wrap(to_int_scalar)
wrapped_to_lgl <- wrap(to_lgl)
wrapped_to_lgl_scalar <- wrap(to_lgl_scalar)
wrapped_to_null <- wrap(to_null)
